# Generated by Django 5.1.2 on 2024-10-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_product_digital"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
