# Generated by Django 5.1.2 on 2024-10-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_shippingaddress_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
