# Generated by Django 5.1.2 on 2024-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_order_session_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="session_key",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
