# Generated by Django 5.1.2 on 2024-10-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_remove_order_session_key_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="https://shophub.s3.eu-north-1.amazonaws.com/products/Smartwatch.jpg",
                upload_to="products/",
            ),
        ),
    ]
